project_id = "comrdypkqpdajjscjwsp"

[functions.create-order]
verify_jwt = false

[functions.hashpay-callback]
verify_jwt = false

[functions.check-payment]
verify_jwt = false

[functions.resend-ticket]
verify_jwt = false
